// dashboard/src/App.svelte
<script>
  import { onMount } from 'svelte';
  import Sidebar from './lib/Sidebar.svelte';
  import StatusBar from './lib/StatusBar.svelte';
  import TopologyView from './lib/TopologyView.svelte';
  import NodeGrid from './lib/NodeGrid.svelte';
  import PacketLog from './lib/PacketLog.svelte';
  import Composer from './lib/Composer.svelte';

  let data = {
    local_id: 0,
    neighbors: [],
    messages: [],
    topology: {}
  };

  let connected = false;
  let screen = "topology";
  const setScreen = (s) => screen = s;
  let selectedNode = null;
  let lastResult = null;
  let timeStr = "00:00:00";

  // Clock
  onMount(() => {
    const updateTime = () => {
      const now = new Date();
      timeStr = now.toISOString().split('T')[1].split('.')[0];
    };
    updateTime();
    const interval = setInterval(updateTime, 1000);
    return () => clearInterval(interval);
  });

  async function fetchData() {
    try {
      const res = await fetch('/api/data');
      if (res.ok) {
        data = await res.json();
        connected = true;
      } else {
        connected = false;
      }
    } catch (e) {
      connected = false;
    }
  }

  onMount(() => {
    fetchData();
    const interval = setInterval(fetchData, 500);
    return () => clearInterval(interval);
  });

  function getPrrState(prr) {
    if (prr >= 0.76) return "ok";
    if (prr >= 0.26) return "relay";
    return "lost";
  }

  $: nodes = (() => {
    const hubId = "HUB";
    const result = [];
    const nodeMap = new Map();

    const addNode = (id, obj) => {
      if (!nodeMap.has(id)) {
        nodeMap.set(id, obj);
        result.push(obj);
      }
      return nodeMap.get(id);
    };

    addNode(data.local_id, {
      id: hubId,
      label: `N-${(data.local_id || 0).toString().padStart(2, '0')}`,
      prr: 1.0,
      state: "ok",
      dbm: 0,
      hops: 0,
      x: 50,
      y: 50
    });

    if (data.neighbors) {
      data.neighbors.forEach(n => {
        addNode(n.id, {
          id: `N-${n.id.toString().padStart(2, '0')}`,
          label: `N-${n.id.toString().padStart(2, '0')}`,
          prr: n.prr,
          state: getPrrState(n.prr),
          dbm: n.rssi_dbm,
          hops: 1
        });
      });
    }

    if (data.topology) {
      Object.entries(data.topology).forEach(([sourceStr, edges]) => {
        const sourceId = parseInt(sourceStr, 10);
        addNode(sourceId, {
          id: `N-${sourceId.toString().padStart(2, '0')}`,
          label: `N-${sourceId.toString().padStart(2, '0')}`,
          prr: 0,
          state: "lost",
          dbm: -100,
          hops: 2
        });
        
        edges.forEach(([targetId, prr]) => {
          addNode(targetId, {
            id: `N-${targetId.toString().padStart(2, '0')}`,
            label: `N-${targetId.toString().padStart(2, '0')}`,
            prr: 0,
            state: "lost",
            dbm: -100,
            hops: 2
          });
        });
      });

      // Simple BFS for hops
      let bfsQueue = [data.local_id];
      let visited = new Set([data.local_id]);
      
      while(bfsQueue.length > 0) {
         let curr = bfsQueue.shift();
         let currNode = nodeMap.get(curr);
         let currHops = currNode ? currNode.hops : 0;
         
         let neighborsOfCurr = [];
         if (curr === data.local_id) {
            neighborsOfCurr = (data.neighbors || []).map(n => n.id);
         } else if (data.topology[curr]) {
            neighborsOfCurr = data.topology[curr].map(link => link[0]);
         }
         
         for (let nId of neighborsOfCurr) {
            if (!visited.has(nId) && nodeMap.has(nId)) {
               visited.add(nId);
               nodeMap.get(nId).hops = currHops + 1;
               bfsQueue.push(nId);
            }
         }
      }
    }

    // Layout
    const hopsArr = [];
    result.forEach(n => {
       if (n.id === "HUB") return;
       let h = n.hops;
       if (!hopsArr[h]) hopsArr[h] = [];
       hopsArr[h].push(n);
    });

    hopsArr.forEach((nodesAtHop, h) => {
       if (!nodesAtHop) return;
       const N = Math.max(nodesAtHop.length, 3);
       const radius = Math.min(20 * h, 45); // cap radius
       nodesAtHop.forEach((n, i) => {
          const angle = (i / N) * 2 * Math.PI + (h * 0.5);
          n.x = 50 + radius * Math.cos(angle);
          n.y = 50 + radius * Math.sin(angle);
       });
    });

    return result;
  })();

  $: meshLinks = (() => {
    let l = [];
    if (data.neighbors) {
       data.neighbors.forEach(n => {
          l.push({ source: "HUB", target: `N-${n.id.toString().padStart(2, '0')}`, prr: n.prr });
       });
    }
    if (data.topology) {
       Object.entries(data.topology).forEach(([sourceStr, edges]) => {
          const sourceId = parseInt(sourceStr, 10);
          const sId = sourceId === data.local_id ? "HUB" : `N-${sourceId.toString().padStart(2, '0')}`;
          
          edges.forEach(([targetId, prr]) => {
             const tId = targetId === data.local_id ? "HUB" : `N-${targetId.toString().padStart(2, '0')}`;
             l.push({ source: sId, target: tId, prr: prr });
          });
       });
    }
    return l;
  })();

  $: formattedMessages = data.messages.map((m, i) => {
    const d = new Date(m.timestamp * 1000);
    const nodeLabel = `N-${m.source.toString().padStart(2, '0')}`;
    const sourceNode = nodes.find(n => n.label === nodeLabel);
    
    return {
      id: m.id || i,
      time: d.toISOString().split('T')[1].split('.')[0],
      node: nodeLabel,
      nodeState: sourceNode ? sourceNode.state : "ok",
      kind: m.image ? "image" : "text",
      payload: m.image ? "IMAGE ATTACHMENT" : (m.text !== null && m.text !== "" ? m.text : "EMPTY"),
      image: m.image,
      result: "RECV"
    };
  }).reverse();

  $: lastEvent = formattedMessages.length > 0 
    ? `${formattedMessages[0].node} · ${formattedMessages[0].kind} · ${formattedMessages[0].result}` 
    : "No recent events";

  async function handleSend({ target, kind, text, image }) {
    // Send to API
    try {
      const res = await fetch('/api/send', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text, image })
      });
      if (res.ok) {
        lastResult = { result: "OK", message: `Packet committed → ${target}.` };
      } else {
        lastResult = { result: "LOST", message: `Packet lost on ${target}. Retry in 200ms.` };
      }
    } catch (e) {
      lastResult = { result: "LOST", message: `Network error. Failed to send.` };
    }
    setTimeout(() => lastResult = null, 4000);
  }
</script>

<div class="shell">
  <Sidebar {screen} {setScreen} {nodes} />
  
  <StatusBar time={timeStr} {lastEvent} onSend={() => screen = "uplink"} nodesCount={nodes.length} />
  
  <div class="shell-main">
    <div style="flex:1;min-height:0;display:flex;position:relative;flex-direction:column">
        {#if screen === "topology"}
          <TopologyView {nodes} links={meshLinks} selected={selectedNode} setSelected={(n) => selectedNode = n} />
        {:else if screen === "nodes"}
          <NodeGrid {nodes} selected={selectedNode} setSelected={(n) => selectedNode = n} />
        {:else if screen === "uplink"}
          <Composer {nodes} onSend={handleSend} {lastResult} entries={formattedMessages} />
        {:else if screen === "log"}
          <PacketLog entries={formattedMessages} />
        {/if}
    </div>
  </div>
</div>

// lost-in-the-mes-h-s-design-system/project/ui_kits/dashboard/App.jsx
/* App.jsx — top-level shell, routing, fake telemetry simulator */

const { useState, useEffect, useRef, useMemo } = React;

const INITIAL_LOG = [
  { id:1, time:"22:14:07", node:"N-04", nodeState:"ok",    kind:"image", payload:"survey_NE_quad.jpg · 1.2MB · 14 chunks", result:"OK" },
  { id:2, time:"22:14:05", node:"N-07", nodeState:"ok",    kind:"text",  payload:"\"holding pattern, awaiting nav\"", result:"OK" },
  { id:3, time:"22:14:03", node:"N-09", nodeState:"relay", kind:"video", payload:"stream_a.h264 · ch.2 · degraded", result:"RELAY" },
  { id:4, time:"22:14:02", node:"N-11", nodeState:"lost",  kind:"image", payload:"survey_NW.jpg · ch.7 dropped · retry 200ms", result:"LOST" },
  { id:5, time:"22:14:01", node:"HUB",  nodeState:"ok",    kind:"route", payload:"→ N-04 → N-07 committed", result:"OK" },
  { id:6, time:"22:13:55", node:"N-13", nodeState:"ok",    kind:"text",  payload:"\"telemetry sync\"", result:"OK" },
  { id:7, time:"22:13:50", node:"N-11", nodeState:"lost",  kind:"text",  payload:"\"beacon lost\"", result:"LOST" },
  { id:8, time:"22:13:44", node:"N-04", nodeState:"ok",    kind:"image", payload:"survey_S.jpg · 0.8MB · 9 chunks", result:"OK" },
];

function App() {
  const [screen, setScreen] = useState("topology");
  const [nodes, setNodes] = useState(INITIAL_NODES);
  const [links] = useState(INITIAL_LINKS);
  const [selected, setSelected] = useState(null);
  const [log, setLog] = useState(INITIAL_LOG);
  const [livePackets, setLivePackets] = useState([]);
  const [lastResult, setLastResult] = useState(null);
  const [time, setTime] = useState("22:14:09");
  const seq = useRef(100);

  /* live clock + small PRR jitter */
  useEffect(() => {
    const id = setInterval(() => {
      setTime(t => {
        const [h,m,s] = t.split(":").map(Number);
        let sx = s + 1, mx = m, hx = h;
        if (sx === 60) { sx = 0; mx += 1; }
        if (mx === 60) { mx = 0; hx += 1; }
        return `${String(hx).padStart(2,"0")}:${String(mx).padStart(2,"0")}:${String(sx).padStart(2,"0")}`;
      });
      setNodes(ns => ns.map(n => {
        if (n.id === "HUB") return n;
        const jitter = (Math.random() - 0.5) * 0.04;
        const prr = Math.max(0, Math.min(1, n.prr + jitter));
        return { ...n, prr, state: stateOfPrr(prr) };
      }));
    }, 1500);
    return () => clearInterval(id);
  }, []);

  /* spawn a packet animation every 2s on a random OK link */
  useEffect(() => {
    const id = setInterval(() => {
      const candidates = links.filter(([a,b,q]) => q >= 0.6);
      if (!candidates.length) return;
      const pick = candidates[Math.floor(Math.random() * candidates.length)];
      const pid = ++seq.current;
      setLivePackets(p => [...p, { id: pid, from: pick[0], to: pick[1], t: 0 }]);
      const start = performance.now();
      const dur = 1200;
      const step = (now) => {
        const t = Math.min(1, (now - start) / dur);
        setLivePackets(p => p.map(x => x.id === pid ? { ...x, t } : x));
        if (t < 1) requestAnimationFrame(step);
        else setLivePackets(p => p.filter(x => x.id !== pid));
      };
      requestAnimationFrame(step);
    }, 1800);
    return () => clearInterval(id);
  }, [links]);

  const handleSend = ({ target, kind, text }) => {
    const node = nodes.find(n => n.id === target);
    if (!node) return;
    const willLand = node.prr >= 0.6;
    const isDegraded = node.prr >= 0.25 && node.prr < 0.6;
    const result = willLand ? "OK" : isDegraded ? "RELAY" : "LOST";
    const payload = kind === "text"
      ? `"${text.slice(0, 40)}${text.length > 40 ? "…" : ""}"`
      : `${kind}_${Math.floor(Math.random()*9000+1000)}.${kind === "image" ? "jpg" : kind === "video" ? "h264" : "bin"} · ${(Math.random()*2+0.4).toFixed(1)}MB`;
    const entry = {
      id: ++seq.current,
      time,
      node: target,
      nodeState: node.state,
      kind,
      payload,
      result,
    };
    setLog(l => [entry, ...l]);
    setLastResult({
      result,
      message: result === "OK" ? `Packet committed → ${target}.`
             : result === "RELAY" ? `Relaying via N-04. PRR degraded.`
             : `Packet lost on ${target}. Retry in 200ms.`,
    });
    setTimeout(() => setLastResult(null), 4000);
  };

  const selectedNode = nodes.find(n => n.id === selected);

  const screens = {
    topology: (
      <>
        <TopologyView nodes={nodes} links={links} selected={selected} setSelected={setSelected} livePackets={livePackets}/>
      </>
    ),
    nodes:    <NodeGrid nodes={nodes} selected={selected} setSelected={setSelected}/>,
    uplink:   <Composer nodes={nodes} onSend={handleSend} lastResult={lastResult}/>,
    log:      <PacketLog entries={log}/>,
    apps:     <UplinkApps onLaunch={() => setScreen("uplink")}/>,
  };

  return (
    <div className="shell">
      <Sidebar screen={screen} setScreen={setScreen} nodes={nodes}/>
      <StatusBar time={time} lastEvent={`${log[0].node} · ${log[0].kind} · ${log[0].result}`} onSend={() => setScreen("uplink")}/>
      <div className="shell-main">
        <TabBar screen={screen} setScreen={setScreen}/>
        <div style={{flex:1,minHeight:0,display:"flex",position:"relative"}}>
          <div style={{flex:1,minHeight:0,display:"flex",flexDirection:"column"}}>
            {screens[screen]}
          </div>
          {selectedNode && screen === "topology" && (
            <NodeInspector node={selectedNode} links={links} nodes={nodes} onClose={() => setSelected(null)}/>
          )}
        </div>
      </div>
    </div>
  );
}

function TabBar({ screen, setScreen }) {
  const tabs = [
    { id: "topology", label: "Topology" },
    { id: "nodes",    label: "Nodes · 14" },
    { id: "uplink",   label: "Uplink" },
    { id: "log",      label: "Log" },
    { id: "apps",     label: "Apps · 4" },
  ];
  return (
    <div className="tabbar">
      {tabs.map(t => (
        <button key={t.id} onClick={() => setScreen(t.id)} className={`tab ${screen === t.id ? "active" : ""}`}>
          {t.label}
        </button>
      ))}
    </div>
  );
}

ReactDOM.createRoot(document.getElementById("root")).render(<App/>);
